{
 "title": "Prometheus",
 "description": "Monitor activity",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "Sum of reads and writes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(node_disk_written_bytes_total[5m]) + rate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Sum of reads and writes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(node_network_transmit_bytes_total[5m]) + rate(node_network_receive_bytes_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "description": "Percent of disk in use",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (1 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "INode Usage",
   "type": "timeseries",
   "description": "INode usage as a percent",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (1 - (node_filesystem_files_free{mountpoint=\"/\"} / node_filesystem_files{mountpoint=\"/\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory in use",
   "type": "timeseries",
   "description": "Current memory usage expressed as percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (1 - (node_memory_MemFree_bytes + node_memory_Cached_bytes) / node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Time CPU spent not in idle over the last minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(node_cpu_seconds_total{mode!=\"idle\"}[2m]) / 4)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}